services:
  web:
    platform: linux/amd64
    build: .

    command: "gunicorn --access-logfile - --error-logfile - --log-level INFO --bind 0.0.0.0:8080 --workers 4 'app:create_app()'"
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://fuckup:fuckup@postgresql/fuckup
      BOT_TOKEN: your_telegram_bot_token
      BOT_URL: your_heroku_app_name
