name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: no-fuckup-timer-bot
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.HOST }}
        username: ${{ env.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: /home/no-fuckup-timer-bot/deploy.sh
